config/routes.rb
Rails.application.routes.draw do
  get '/about' => 'pages#about'

  resources :contacts

  root "pages#home"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def index
		@contacts = Contact.all.order("created_at DESC")
	end

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params_contact)
		if @contact.save
			flash[:success] = "Message sent successfully."
			redirect_to root_path
		else
			render 'new'
			flash[:danger] = "Errors Occured. Message could not send"
		end
	end
	
	private

	def params_contact
		params.require(:contact).permit(:name, :email, :comments)
	end

	def find_contact
		@contact = Contact.find(params[:id])
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
	<% if @contact.errors.any? %>
		<ul>
			<% @contact.errors.full_messages.each do |msg| %>
				<%= content_tag(:div, class: 'alert alert-danger') do %>
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<li><%= msg %></li>	
				<% end %>
				
			<% end %>
		</ul>
	<% end %>


	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :comments %>
		<%= f.text_area :comments, class: 'form-control' %>
	</div>

	<%= f.button :submit, class: 'btn btn-default' %>

<% end %>

app/views/contacts/index.html.erb
<div class="table table-striped table-condensed table-bordered">
	<thead>
		<tr>
			<td>one</td>			
			<td>one</td>			
		</tr>

	</thead>
</div>

app/views/contacts/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="well">
			<h1>New Contact</h1>
			<br>

			<%= render 'form' %>

			<br>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saas1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-brand">
				<i class="fa fa-hand-lizard-o fa-1g"></i>
				<%= link_to 'Dev Match', root_path %>
			</div>
			
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'New Contact', new_contact_path %></li>
				<li><%= link_to 'About', about_path  %></li>
			</ul>
		</div>
	</div>

	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, class: "alert alert-#{name}") do %>
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= msg %>
			<% end %>
		<% end %>


		<%= yield %>	
	</div>
	

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
	<h1>Welcome to Dev Match</h1>
	<p>A membership site for developers and entrepreneurs meet each each other</p>
</div>